#include<iostream.h>
#include<string.h>
void main()
{
char hari;
cout<<masukkan kode hari (A-G) :";
cin>>hari;

if(hari=='a'||hari=='A')
{
cout<<"senin";}
else if (bari=='b'||hari=='B')
{
cout<< "selasa;}
else if (hari== 'c'||hari== 'c')
{
cout<<"rabu";}
else if(hari=='d'||hari=='D')
{
cout<< "kamis";}
else if (hari=='e'||hari=='E')
{
cout<< "jumat";}
else if (hari=='f'||hari=='F')
{
cout<<"sabtu";}
else if (hari=='g'||hari=='G')
{
cout<<"minggu";}
else
cout"maaf kode hari yang anda masukkan salah";
return 0;
}

